# Uncomment to enable encoder
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the Lily58 OLED Display
CONFIG_ZMK_DISPLAY=y

CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_DISPLAY_TICK_PERIOD_MS=20
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# Set name of the keyboard
CONFIG_ZMK_KEYBOARD_NAME="Thoth"
CONFIG_BT_DEVICE_NAME="Thoth"

# Clear the bonds on start(Have to pair again after each reboot of the keyboard)
#CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=y

#Enable Soft Off feature
CONFIG_ZMK_PM_SOFT_OFF=y
